SELECT A.RG, P.NOME, COUNT(DISTINCT EVENTOS)
(SELECT A.RG, P.NOME, C.EVENTO AS EVENTOS 
	FROM ((ATLETA A JOIN PESSOA P ON A.RG = P.RG) JOIN COMPETE C ON A.RG = C.ATLETA)
UNION
SELECT A.RG, P.NOME, R.EVENTO AS EVENTOS 
	FROM (((ATLETA A JOIN PESSOA P ON A.RG = P.RG) JOIN EQUIPE E ON A.EQUIPE = E.NOME)) JOIN REPRESENTA R ON R.EQUIPE = E.NOME))

	GROUP BY A.RG
	HAVING COUNT(DISTINCT EVENTOS) > 3;